  version: '3.3'

  services:
    db:
      build:
        context: .
        dockerfile: Dockerfile_mysql
      container_name: mysql-db2
      environment:
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - "3307:3306"

    demo:
      build:
            context: .
            dockerfile: Dockerfile_app
      container_name: dream-spring-boot-app
      depends_on:
        - db
      ports:
        - "8000:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3307/mydb
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root