version: '3'
services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build: .
    image: my-app
    container_name: app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/example
      SPRING_DATASOURCE_USERNAME: example
      SPRING_DATASOURCE_PASSWORD: example
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  db-data:
